### PR TITLE
Fix mangling of input to action

### LINKED ISSUE #1: Fix mangling of input to the action
During testing, it was noticed that the prompt inputs configured for the action are being processed without proper line breaks when the request is finally sent to ChatGPT. This is _likely_ happening because the input is being passed through environment variables, where line breaks are unacceptable. An alternative method that doesn't involve this mangling will be required.

An option that occurs to me is to avoid using Docker (which is why env vars are being used), and instead set up a Ruby env for the action and run the script directly using input fed unalterted into the Ruby script using some method... maybe simply dumping the input as JSON into a file before executing the Ruby script.

### PR DESCRIPTION
**Pull request by yash-learner**
Fixes #1

### CODE REVIEW

File: app/open_ai_client.rb [hunk 1]
```diff
@@ -28,22 +35,18 @@ def replace_placeholder(text, placeholder, value)
...
+#{@role_prompt}
 
-#{ENV.fetch("INPUT_DESCRIPTION", "${INPUT_DESCRIPTION}")}
+#{@input_description}
 
-#{ENV.fetch("USER_PROMPT", "${USER_PROMPT}")}
+#{@user_prompt}
 
-#{ENV.fetch("OUTPUT_DESCRIPTION", "${OUTPUT_DESCRIPTION}")}
+#{@output_description}
```
Comment (bodhish) [inline app/open_ai_client.rb]: Why would override these? 

The reason for this setup was to allow admins to add a `SYSTEM_PROMPT` with custom ordering of these keys;

File: app/open_ai_client.rb [hunk 2]
```diff
@@ -28,22 +35,18 @@ def replace_placeholder(text, placeholder, value)
 
   def prompt
     @system_prompt
-    .gsub("${ROLE_PROMPT}", default_role_prompt)
-    .gsub("${INPUT_DESCRIPTION}", default_input_prompt)
-    .gsub("${USER_PROMPT}", default_user_prompt)
-    .gsub("${SUBMISSION}", "#{Submission.new.checklist}")
-    .gsub("${OUTPUT_DESCRIPTION}", default_output_prompt)
+    .gsub("@@SUBMISSION@@", "#{Submission.new.checklist}")
```
Comment (bodhish) [inline app/open_ai_client.rb]: `${}` is a common syntax we use across the lms for system replacement; Why create a new one `@@`?

File: app/open_ai_client.rb [hunk 3]
```diff
@@ -1,11 +1,18 @@
...
+require 'json'
 
 class OpenAIClient
   def initialize
     @client = OpenAI::Client.new
     @model = ENV.fetch('OPEN_AI_MODEL', "gpt-3.5-turbo")
     @temperature = ENV.fetch('OPEN_AI_TEMPERATURE', 0.1)
-    @system_prompt = ENV.fetch('SYSTEM_PROMPT', system_prompt_default)
+
+    prompts = JSON.parse(File.read("#{ENV['GITHUB_WORKSPACE']}/prompts.json"))
```
Comment (bodhish) [inline app/open_ai_client.rb]: Not sure if `@prompts` is the right variable name as the file will also have to deal with other variables

File: app/open_ai_client.rb [hunk 4]
```diff
@@ -1,11 +1,18 @@
 require 'openai'
+require 'json'
 
 class OpenAIClient
   def initialize
     @client = OpenAI::Client.new
     @model = ENV.fetch('OPEN_AI_MODEL', "gpt-3.5-turbo")
     @temperature = ENV.fetch('OPEN_AI_TEMPERATURE', 0.1)
```
Comment (bodhish) [inline app/open_ai_client.rb]: Why not read all ENV from the file 🤔

File: app/graphql_schema.json
Comment (bodhish) [inline app/graphql_schema.json:1]: Lets not format this file; Its system generated when replacing it next it would add unnecessary diff;

File: action.yml [hunk 5]
```diff
@@ -41,3 +38,48 @@ inputs:
   REVIEW_BOT_USER_TOKEN:
     description: 'Token used for authorization when sending the reviews to the LMS'
     required: true
+runs:
+  using: 'composite'
+  steps:
+    - name: 'Checkout'
+      uses: 'actions/checkout@v3'
```
Comment (bodhish) [inline action.yml]: Use the latest

File: app/pupilfirst_api.rb [hunk 6]
```diff
@@ -13,7 +13,9 @@ def headers(_context)
       end
     end
 
-    Schema = GraphQL::Client.load_schema('/app/graphql_schema.json')
+    schema_path = "#{ENV['GITHUB_ACTION_PATH']}/app/graphql_schema.json"
```
Comment (bodhish) [inline app/pupilfirst_api.rb]: Do document this somewhere, else it would be hard to run locally; 
I think you should add an `example.env` file so that others can also run the action locally;

**Review by bodhish — CHANGES_REQUESTED** [review]

File: app/open_ai_client.rb (hunk 2 above)
Comment (yash-learner) [reply app/open_ai_client.rb]: @bodhish 

This line https://github.com/yash-learner/ai-review-action/blob/f53093da0dda61410c53bd8773fec4e2fb8ae267/action.yml#L72 is trying to expand replace ${submission} with a submission variable, but that does not exist in `test.yml`  and it's getting filtered out. We replace that in the ruby code.

You can see logs of this action `${submission} is filtered out for above reason ` https://github.com/Pupilfirst-VTA/student-110587/actions/runs/6088097986/job/16525167724#step:4:227

`@@SUBMISSION@@` is uncommon to get replaced

File: app/graphql_schema.json
Comment (yash-learner) [reply app/graphql_schema.json:1]: Actually, I did not format it. I just copy and pasted the system generated schema from LMS to here while working.

Anyway, I will revert it to the old

File: app/open_ai_client.rb (hunk 2 above)
Comment (yash-learner) [reply app/open_ai_client.rb]: Will try with `\` slash in front of `$`

Comment (yash-learner) [reply app/open_ai_client.rb]: Which one do think the best approach if `\` works

- Asking user to use \ when using ${} in target github action.
- Replacing the ${} with /${} in workflow step before processing and replace the /${} with ${} in code

File: example.env [hunk 7]
```diff
@@ -0,0 +1 @@
+GITHUB_ACTION_PATH=/path/to/your/project/root
```
Comment (bodhish) [inline example.env]: Would be great if you can document the other variables also.

File: entrypoint.rb [hunk 8]
```diff
@@ -23,4 +23,5 @@ def generate_response
     end
 end
 
+
```
Comment (bodhish) [inline entrypoint.rb]: Do we need this 🤔

File: action.yml [hunk 9]
```diff
@@ -41,3 +38,23 @@ inputs:
   REVIEW_BOT_USER_TOKEN:
     description: 'Token used for authorization when sending the reviews to the LMS'
     required: true
+runs:
+  using: 'composite'
```
Comment (bodhish) [inline action.yml]: Question: Do we need the composite action 🤔; I mean can't we work with the docker action itself since we are reading the workflow file; From my understanding it the file will be accessible inside the docker build;

**Review by bodhish — CHANGES_REQUESTED** [review]

**Review by bodhish — COMMENTED** [review]
- [x] Make sure we do a squash and merge as the PR has a lot of test commits;

File: action.yml (hunk 9 above)
Comment (yash-learner) [reply action.yml]: Yes

Reverted to Docker based action

File: .github/workflows/test.yml [hunk 10]
```diff
@@ -10,15 +10,19 @@ env:
...
 jobs:
   test: # make sure the action works on a clean machine without building
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: ./
+      - uses: actions/checkout@v4
+
+      - name: AI auto review
+        id: ai-review
```
Comment (bodhish) [inline .github/workflows/test.yml]:
```suggestion
      - uses: actions/checkout@v4
      - name: AI auto review
        id: ai-review
```

File: example.env [hunk 11]
```diff
@@ -0,0 +1,9 @@
+OPENAI_ACCESS_TOKEN=your_openai_access_token
+
+OPENAI_ORGANIZATION_ID=your_openai_organization_id
+
+REVIEW_END_POINT=review_end_point_url
+
+WORKFLOW_FILE_PATH=/path/to/workflow/file
+
+TEST_MODE-false
```
Comment (bodhish) [inline example.env]:
```suggestion
TEST_MODE=false
```

**Review by bodhish — APPROVED** [review]

File: Dockerfile [hunk 12]
```diff
@@ -1,6 +1,6 @@
 FROM ruby:3.1
 
-RUN gem install graphql -v 2.0.27
+RUN gem instal graphql -v 2.0.27
```
Comment (bodhish) [inline Dockerfile]:
```suggestion
RUN gem install graphql -v 2.0.27
```

File: app/open_ai_client.rb [hunk 13]
```diff
@@ -1,11 +1,18 @@
...
   def initialize
     @client = OpenAI::Client.new
-    @model = ENV.fetch('OPEN_AI_MODEL', "gpt-3.5-turbo")
-    @temperature = ENV.fetch('OPEN_AI_TEMPERATURE', 0.1)
-    @system_prompt = ENV.fetch('SYSTEM_PROMPT', system_prompt_default)
+
+    content = YAML.safe_load(File.read(ENV.fetch('WORKFLOW_FILE_PATH', './.github/workflows/ci.js.yml')))
+    @config = content.dig('jobs', 'test', 'steps').find do |step|
+      ( step['uses']&.include?('pupilfirst/ai-review-action') || step['id']&.include?('ai-review') )
+    end.fetch('with', {})
```
Comment (bodhish) [inline app/open_ai_client.rb]: The code would be more readable if we extract it out into a different function. 
```suggestion
    @config = extract_relevant_step_configuration
```

```rb
  def extract_relevant_step_configuration
    # Load workflow YAML file from the path specified in the environment variable or the default path.
    file_path = ENV.fetch('WORKFLOW_FILE_PATH', './.github/workflows/ci.js.yml')
    content = YAML.safe_load(File.read(file_path))
    # Find the job step that uses 'pupilfirst/ai-review-action' or has an ID containing 'ai-review'.
    content.dig('jobs', 'test', 'steps').find do |step|
      step['uses']&.include?('pupilfirst/ai-review-action') || step['id']&.include?('ai-review')
    end.fetch('with', {})
  end
  ```

**Review by bodhish — APPROVED** [review]

**Review by bodhish — APPROVED** [review]
